-- FutureCrest CRM: real group chat schema
-- Run this once in Supabase SQL Editor before enabling Group Chat UI.

create table if not exists public.crm_chat_groups (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.crm_chat_group_members (
  group_id uuid not null references public.crm_chat_groups(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (group_id, user_id)
);

create table if not exists public.crm_chat_group_messages (
  id bigint generated by default as identity primary key,
  group_id uuid not null references public.crm_chat_groups(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  message text not null default '',
  attachment_url text,
  created_at timestamptz not null default now()
);

create index if not exists crm_chat_group_messages_group_idx
  on public.crm_chat_group_messages(group_id, created_at);

alter table public.crm_chat_groups enable row level security;
alter table public.crm_chat_group_members enable row level security;
alter table public.crm_chat_group_messages enable row level security;

-- Membership-based access. These policies intentionally use auth.uid().
drop policy if exists "group members can read groups" on public.crm_chat_groups;
create policy "group members can read groups"
  on public.crm_chat_groups for select to authenticated
  using (exists (
    select 1 from public.crm_chat_group_members m
    where m.group_id = id and m.user_id = auth.uid()
  ));

drop policy if exists "authenticated can create groups" on public.crm_chat_groups;
create policy "authenticated can create groups"
  on public.crm_chat_groups for insert to authenticated
  with check (created_by = auth.uid());

drop policy if exists "members can read membership" on public.crm_chat_group_members;
create policy "members can read membership"
  on public.crm_chat_group_members for select to authenticated
  using (exists (
    select 1 from public.crm_chat_group_members me
    where me.group_id = group_id and me.user_id = auth.uid()
  ));

drop policy if exists "members can insert membership" on public.crm_chat_group_members;
create policy "members can insert membership"
  on public.crm_chat_group_members for insert to authenticated
  with check (exists (
    select 1 from public.crm_chat_groups g
    where g.id = group_id and g.created_by = auth.uid()
  ) or user_id = auth.uid());

drop policy if exists "members can read group messages" on public.crm_chat_group_messages;
create policy "members can read group messages"
  on public.crm_chat_group_messages for select to authenticated
  using (exists (
    select 1 from public.crm_chat_group_members m
    where m.group_id = group_id and m.user_id = auth.uid()
  ));

drop policy if exists "members can send group messages" on public.crm_chat_group_messages;
create policy "members can send group messages"
  on public.crm_chat_group_messages for insert to authenticated
  with check (
    sender_id = auth.uid() and exists (
      select 1 from public.crm_chat_group_members m
      where m.group_id = group_id and m.user_id = auth.uid()
    )
  );
